name: Latest Changes

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # To allow latest-changes to commit to master
          token: ${{ secrets.LATEST_CHANGES_TOKEN }}
      - uses: docker://tiangolo/latest-changes:0.0.3
        with:
          token: ${{ secrets.LATEST_CHANGES_TOKEN }}
          latest_changes_file: docs/release-notes.md
          latest_changes_header: '## Latest Changes\n\n'
          debug_logs: true
