name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-publish
      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install build
      - name: Build distribution
        run: python -m build
      # TODO: enable publishing when going live
      # - name: Publish
      #   uses: pypa/gh-action-pypi-publish@v1.8.5
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
